// frontend/src/Book/Book.tsx
import {BookType} from "./Book.type";
import {createSignal, For, onMount, Show} from "solid-js";
import Rest from "../Rest";
import {BOOK_API, DOWNLOAD_API, DOWNLOAD_ORIGINAL_API} from "../Api/Api";
import defaultCover from "../assets/cover.jpg";
import download_icon from "../assets/download.svg";
import Badge from "../UI/Badge";
import {LinkButton} from "../UI/Button";
import {useParams} from "solid-app-router";

const Book = () => {
  const [book, setBook] = createSignal<BookType | null>(null);
  const path = useParams<{ readonly book: string }>();
  const getBook = async (): Promise<BookType> => {
    const response = await Rest.get<BookType>(BOOK_API(path.book));
    return response.data;
  };

  onMount(() => {
    getBook()
      .then(book => setBook(book));
  });

  return (
    <Show when={book() !== null} fallback={<h1>Loading...</h1>}>
      <div class="mt-10 flex justify-center">
        <div class="grid max-w-[80%]">
          <img
            alt={`cover picture of ${book()!.title}`}
            src={book()!.cover !== null ? `data:image/jpeg;base64,${book()!.cover}` : defaultCover}
            width="270"
            height="470"
          />
          <div class="grid-cols-1 grid h-max">
            <div class="m-5">
              <h1>Authors:</h1>
              <For each={book()!.authors}>
                {(author) => (
                  <Badge
                    onClick={() => console.log(" router.push(`/search?q=${encodeURIComponent(author.name)}`)")}
                    text={author.name}
                  />)}
              </For>
            </div>
            <div class="m-5">
              <h1>Subjects:</h1>
              <For each={book()!.subjects}>
                {(subject) => (
                  <Badge
                    onClick={() => console.log(" router.push(`/search?q=${encodeURIComponent(subject.name)}`)")}
                    text={subject.name}
                  />)}
              </For>
            </div>
          </div>
          <div class="col-start-1 col-end-3 mt-5 flex justify-self-stretch">
            <LinkButton
              href={DOWNLOAD_API(book()!.id)}
              download={true}
              className="w-6/12"
            >
              <img
                class="dark:invert invert-0 h-8 mr-1"
                src={download_icon}
                alt="download"
              /> Download
            </LinkButton>
            <LinkButton
              href={DOWNLOAD_ORIGINAL_API(book()!.id)}
              download={true}
              className="w-6/12"
            >
              <img
                class="dark:invert invert-0 h-8 mr-1"
                src={download_icon}
                alt="download"
              /> Download Original
            </LinkButton>
          </div>
        </div>
      </div>
    </Show>
  );
};

export default Book;

// frontend/src/Book/Book.vue
<script setup lang="ts">
import Badge from '@/UI/Badge.vue';
import Button from '@/UI/Button.vue';
import type {BookType} from "@/Book/Book.type";
import router from "@/router";
import defaultCover from '../assets/cover.jpg';
import {ref} from "vue-demi";
import Rest from "../Rest";
import {onMounted} from "vue";
import {ApplicationStore} from "@/stores/ApplicationStore";
import {CollectionStore} from "@/stores/CollectionStore";
import {BOOK_API, DOWNLOAD_API} from "@/api/Api";
import download_icon from '@/assets/download.svg';

const title: string = router.currentRoute.value.params.title as string;
const book = ref<BookType>();
const getBook = async (): Promise<BookType> => {
  const response = await Rest.get<BookType>(BOOK_API(title));
  return response.data;
};

const applicationStore = ApplicationStore();
const collectionStore = CollectionStore();
onMounted(() => {
  applicationStore.setHeaderText(title);
  const storedBook = Object.values(collectionStore.collections).flat().find(bo => bo.title === title);
  if (storedBook !== undefined) {
    book.value = storedBook;
  } else {
    getBook().then(r => book.value = r);
  }
});

</script>


<template>
  <div class="mt-10 flex justify-center">
    <div class="grid max-w-[80%]" v-if="book !== undefined">
      <img
          v-bind="{
            src: book.cover !== null ? `data:image/jpeg;base64,${book.cover}` : defaultCover,
            alt: `cover picture of ${book.title}`
          }"
          width="270"
          height="470"
      />
      <div class="grid-cols-1 grid h-max">
        <div class="m-5">
          <h1>Authors:</h1>
          <Badge
              v-for="author in book.authors"
              v-bind="{
               onClick: () => router.push(`/search?q=${encodeURIComponent(author.name)}`),
               text: author.name
             }"
          />
        </div>
        <div class="m-5">
          <h1>Subjects:</h1>
          <Badge
              v-for="subject in book.subjects"
              v-bind="{
               onClick: () => router.push(`/search?q=${encodeURIComponent(subject.name)}`),
               text: subject.name
             }"
          />
        </div>
      </div>
      <div class="col-start-1 col-end-3 mt-5 flex justify-self-stretch">
        <Button
            v-bind="{
              href: DOWNLOAD_API(book.id),
              download: `${book.title}.epub`
            }"
            button-type="link">
          <img
              class="dark:invert invert-0 h-8 mr-1"
              v-bind="{
              src: download_icon
            }"
              alt="download"
          /> Download
        </Button>
      </div>
    </div>
  </div>
</template>
