// frontend/src/Header/Header.vue
<script setup lang="ts">
import Button from '@/UI/Button.vue';
import Upload from '@/Upload/Upload.vue';
import router from "@/router";
import {ref} from "vue-demi";
import {onMounted, onUnmounted} from "vue";
import {ApplicationStore} from '@/stores/ApplicationStore';
import upload_icon from '@/assets/upload.svg';

let isDarkMode = ref<boolean>(window.matchMedia('(prefers-color-scheme: dark)').matches);

const setDarkClass = () => {
  if (isDarkMode.value) {
    document.documentElement.classList.add('dark');
  } else {
    document.documentElement.classList.remove('dark');
  }
};

const setDark = (): void => {
  isDarkMode.value = !isDarkMode.value;
  setDarkClass();
};

onMounted(() => {
  setDarkClass();
});
const uploadFile = ref<boolean>(false);
const setUploadFile = (value: boolean) => {
  uploadFile.value = value;
};

const store = ApplicationStore();
let search = ref<string>("");
let timer: null | number = null;

const clearTimer = () => {
  if (timer !== null) {
    window.clearTimeout(timer);
  }
};

const onInput = (inputEvent: Event) => {
  const target = inputEvent.target as HTMLInputElement;
  search.value = target.value;
  if (target.value === "") {
    clearTimer();
    router.push("/");
  } else {
    store.setHeaderText(`Search: ${search.value}`);
    if (timer !== null) {
      window.clearTimeout(timer);
    }
    timer = window.setTimeout(() => router.push(`/search?q=${encodeURIComponent(search.value)}`),
        500);
  }
};

onMounted(() => {
  store.$subscribe((_, store) => document.title = `E-Book: ${store.headerText}`);
  router.isReady().then(() => {
    if (!Array.isArray(router.currentRoute.value.query.q)) {
      search.value = router.currentRoute.value.query.q || "";
    }
  });
});

onUnmounted(() => {
  clearTimer();
});

</script>

<template>
  <Upload v-if="uploadFile" v-bind="{onClose: () => setUploadFile(false)}"/>
  <div class="flex flex-row justify-between border-b-2">
    <div>
      <Button button-type="default" v-bind="{onClick: () => router.push('/')}">
        Home
      </Button>
      <Button button-type="default" v-bind="{onClick: setDark}">
        {{ isDarkMode ? 'Light mode' : 'Dark mode' }}
      </Button>
    </div>
    <h1 class="text-5xl m-2 font-bold break-all">{{ store.headerText }}</h1>
    <Button button-type="primary" v-bind="{onClick: ()=> setUploadFile(true)}">
      <img
          class="dark:invert invert-0 h-8 mr-1"
          v-bind="{
              src: upload_icon
            }"
          alt="upload"
      /> Upload!
    </Button>
  </div>
  <input
      class="w-[100%] text-5xl bg-slate-300 dark:bg-slate-700"
      placeholder="Search Books, Authors and Subjects"
      v-on:input="onInput"
      v-bind="{
        value: search,
      }"
  />
</template>

// frontend/src/Header/Header.tsx
import { Component, createSignal, onMount, Show } from 'solid-js';
import Upload from '../Upload/Upload';
import { Button, PrimaryButton } from '../UI/Button';
import uploadIcon from '../assets/upload.svg';
import { useNavigate } from 'solid-app-router';
import { headerStore, setHeaderStore } from '../Store/HeaderStore';

const Header: Component = () => {
  const navigate = useNavigate();
  const [isDarkMode, setDarkMode] = createSignal<boolean>(window.matchMedia('(prefers-color-scheme: dark)').matches);
  const [showUploadModal, setShowUploadModal] = createSignal<boolean>(false);
  const [search, setSearch] = createSignal<string>('');

  const setDarkClass = () => {
    if (isDarkMode()) {
      document.documentElement.classList.add('dark');
    } else {
      document.documentElement.classList.remove('dark');
    }
  };

  const setDark = (): void => {
    setDarkMode(old => !old);
    setDarkClass();
  };

  onMount(() => {
    setDarkClass();
  });

  const [timer, setTimer] = createSignal<number | null>(null);
  const setSearchValue = (inputValue: string) => {
    setSearch(inputValue);
    if (timer() == null) {
      setTimer(setTimeout(() => {
        setHeaderStore({ search: search() });
        setTimer(null);
      }, 1000));
    }
  };

  return (
    <>
      <Show when={showUploadModal()}>
        <Upload onClose={() => setShowUploadModal(false)}/>
      </Show>
      <div class="flex flex-row justify-between border-b-2">
        <div>
          <Button onClick={() => navigate('/')}>
            Home
          </Button>
          <Button onClick={setDark}>
            {isDarkMode() ? 'Light mode' : 'Dark mode'}
          </Button>
        </div>
        <h1 class="text-5xl m-2 font-bold break-all">{headerStore.title}</h1>
        <PrimaryButton onClick={() => setShowUploadModal(true)}>
          <img
            class="dark:invert invert-0 h-8 mr-1"
            src={uploadIcon}
            alt="upload"
          /> Upload!
        </PrimaryButton>
      </div>
      <input
        class="w-[100%] text-5xl bg-slate-300 dark:bg-slate-700"
        placeholder="Search Books, Authors and Subjects"
        value={search()}
        onInput={e => setSearchValue(e.currentTarget.value)}
      />
    </>
  );
};

export default Header;
