// frontend/src/Search/Search.vue
<script setup lang="ts">
import type {BookType} from "@/Book/Book.type";
import ItemCard from '@/UI/ItemCard.vue';
import {ref, type Ref} from "vue-demi";
import Rest from "../Rest";
import router from "@/router";
import {onMounted, onUnmounted, watch} from "vue";
import {ApplicationStore} from "@/stores/ApplicationStore";
import type {LocationQueryValue} from "vue-router";
import {SEARCH_API} from "@/api/Api";

const books: Ref<BookType[]> = ref([]);
const loading = ref<boolean>(false);
const page = ref<number>(1);
const allLoaded = ref<boolean>(false);
const searchBooks = async (search: LocationQueryValue | LocationQueryValue[], currentPage: number): Promise<void> => {
  if (search === null || Array.isArray(search)) {
    return Promise.reject();
  }
  loading.value = true;
  const response = await Rest.get<BookType[]>(SEARCH_API(search, currentPage));
  const data = response.data;
  if (data.length > 0) {
    if (currentPage === 1) {
      books.value = data;
      allLoaded.value = false;
      window.setTimeout(() => shouldLoadNextPage(), 50);
    } else {
      books.value = [...books.value, ...data];
    }
    page.value = currentPage + 1;
    loading.value = false;
  } else {
    allLoaded.value = true;
  }
};
const store = ApplicationStore();
const watchCleaner = watch(router.currentRoute, (newRoute, _) => {
  if (newRoute.query.q !== undefined) {
    searchBooks(newRoute.query.q, 1);
  }
});
const openItem = (book: BookType): void => {
  router.push(`/book/${book.title}`);
};

onMounted(() => {
  store.setHeaderText(`Search: ${router.currentRoute.value.query.q}`);
  searchBooks(router.currentRoute.value.query.q, 1);
});
const search = () => {
  searchBooks(router.currentRoute.value.query.q, page.value);
};
const shouldLoadNextPage = (): void => {
  const element = document.querySelector('#loading-trigger');
  const position = element?.getBoundingClientRect();

  if (position !== undefined && !loading.value && position.top >= 0 && position.bottom <= window.innerHeight) {
    search();
  }
};
window.addEventListener('scroll', shouldLoadNextPage);
onUnmounted(() => {
  watchCleaner();
  window.removeEventListener('scroll', shouldLoadNextPage);
});


</script>
<template>
  <div class="flex flex-wrap flex-row justify-center">
    <ItemCard
        v-for="book in books"
        v-bind="{
          name: book.title,
          cover: book.cover,
          id: book.id,
          onClick: () => openItem(book)
        }"
        item-type="book"
    />
  </div>
  <div @click="search" v-if="!allLoaded" id="loading-trigger"
       class="m-5 border cursor-pointer text-center text-5xl">Load More
  </div>
</template>

// frontend/src/Search/Search.tsx
import { createEffect, createSignal, on, onCleanup, onMount, Show } from 'solid-js';
import { setHeaderTitle } from '../Store/HeaderStore';
import Rest from '../Rest';
import { SEARCH_API } from '../Api/Api';
import ItemGrid from '../UI/ItemGrid';
import { searchStore, setSearchStore } from '../Store/SearchStore';
import { BookType } from '../Book/Book.type';

const Search = () => {
  const [loading, setLoading] = createSignal<boolean>(false);

  onMount(() => {
    setHeaderTitle(`Search: ${searchStore.search}`);
    window.addEventListener('scroll', shouldLoadNextPage);
    search();
  });

  createEffect(on(() => searchStore.search, (value, prev) => {
    if (prev !== undefined) {
      resetSearch();
    }
  }));

  const resetSearch = () => {
    if (!loading()) {
      setHeaderTitle(`Search: ${searchStore.search}`);
      search();
    } else {
      setTimeout(resetSearch, 200);
    }
  };

  const search = () => {
    if (!searchStore.allLoaded && !loading() && searchStore.search.trim() !== '') {
      setLoading(true);
      getBooks(searchStore.page).then(r => {
        if (r.length > 0) {
          setSearchStore({
            page: searchStore.page + 1,
            books: [...searchStore.books, ...r]
          });
          window.setTimeout(() => shouldLoadNextPage(), 50);
        } else if (r.length === 0 || r.length > 32) {
          setSearchStore({ allLoaded: true });
        }
        setLoading(false);
      });
    }
  };

  const getBooks = async (page: number): Promise<BookType[]> => {
    const response = await Rest.get<BookType[]>(SEARCH_API(searchStore.search, page));
    return response.data;
  };

  const shouldLoadNextPage = (): void => {
    const element = document.querySelector('#loading-trigger');
    const position = element?.getBoundingClientRect();
    if (position !== undefined && position.top >= 0 && position.bottom <= window.innerHeight) {
      search();
    }
  };

  onCleanup(() => {
    window.removeEventListener('scroll', shouldLoadNextPage);
  });

  return (
    <>
      <ItemGrid
        items={searchStore.books.map(book => ({
          id: book.id,
          title: book.title,
          cover: book.cover,
          itemType: 'book',
          bookCount: 1
        }))}
      />
      <Show when={!searchStore.allLoaded}>
        <div
          id="loading-trigger"
          onClick={() => search()}
          class="m-5 border cursor-pointer text-center text-5xl"
        >
          Load More
        </div>
      </Show>
    </>
  );
};

export default Search;
