// frontend/src/Library/Library.tsx
import React, {useEffect, useState} from 'react';
import {LibraryItemType} from "./LibraryItem.type";
import {useDispatch, useSelector} from "react-redux";
import {AppStore} from "../Store/Store.types";
import {LibraryItemReducer} from "../Reducers/LibraryItemReducer";
import {ApplicationReducer} from "../Reducers/HeaderReducer";
import ItemsGrid from "../UI/ItemsGrid";
import {useNavigate} from "react-router-dom";
import Rest from "../Rest";

const Library = (): JSX.Element => {
  const items = useSelector<AppStore, LibraryItemType[]>((store): LibraryItemType[] => store.libraryItems.items);

  const [loadingDiv, setLoadingDiv] = useState<boolean>(false);
  const getLibraryItems = async (page: number): Promise<LibraryItemType[]> => {
    const response = await Rest.get<LibraryItemType[]>(`/all?page=${page}`);
    return response.data;
  };

  const shouldLoadNextPage = (): void => {
    const element = document.querySelector('#loading-trigger');
    const position = element?.getBoundingClientRect();

    if (position !== undefined && position.top >= 0 && position.bottom <= window.innerHeight) {
      setLoadingDiv(true);
    } else {
      setLoadingDiv(false);
    }
  };

  window.addEventListener('scroll', shouldLoadNextPage);
  const page = useSelector<AppStore, number>((store): number => store.libraryItems.page);
  const allLoaded = useSelector<AppStore, boolean>((store): boolean => store.libraryItems.allItemsLoaded);
  const dispatch = useDispatch();
  useEffect((): void => {
    if (loadingDiv && !allLoaded) {
      setLoadingDiv(false);
      getLibraryItems(page + 1)
        .then((r): void => {
          if (r.length === 0) {
            dispatch(LibraryItemReducer.actions.setAllLoaded(true));
          } else {
            dispatch(LibraryItemReducer.actions.addAll(r));
          }
        });
      dispatch(LibraryItemReducer.actions.setPage(page + 1));
    }
  }, [loadingDiv]);

  useEffect(() => {
    shouldLoadNextPage();
  }, [items]);

  useEffect((): (() => void) => {
    dispatch(ApplicationReducer.actions.reset());
    shouldLoadNextPage();
    return (): void => {
      window.removeEventListener('scroll', shouldLoadNextPage);
    };
  }, []);
  const navigator = useNavigate();
  const openItem = (item: LibraryItemType): void => {
    navigator(`/${item.itemType}/${item.title}`);
  };


  return (
    <>
      <ItemsGrid<LibraryItemType> onClick={(item): void => openItem(item)} items={items}/>
      {allLoaded ? null : <div id="loading-trigger" className="m-5 text-center text-5xl">Loading....</div>}
    </>
  );
};

export default Library;

// frontend/src/Library/Library.vue
<script setup lang="ts">

import type {LibraryItemType} from './LibraryItem.type';
import ItemsGrid from '../UI/ItemsGrid.vue';
import Rest from "../Rest";
import router from "@/router";
import {onMounted, onUnmounted} from "vue";
import {ApplicationStore} from "@/stores/ApplicationStore";
import {type LibraryItemStoreType, LibraryStore} from "@/stores/LibraryStore";
import {ref, type UnwrapRef} from "vue-demi";


const libraryStore = LibraryStore();
const items = ref<LibraryItemType[]>(libraryStore.items);
const getLibraryItems = async (page: number): Promise<LibraryItemType[]> => {
  const response = await Rest.get<LibraryItemType[]>(`/api/all?page=${page}`);
  return response.data;
};

const openItem = (item: LibraryItemType) => {
  router.push(`/${item.itemType}/${item.title}`);
};

const loading = ref<boolean>(false);
const page = ref<number>(libraryStore.page);

const shouldLoadNextPage = (): void => {
  const element = document.querySelector('#loading-trigger');
  const position = element?.getBoundingClientRect();

  if (position !== undefined && !loading.value && position.top >= 0 && position.bottom <= window.innerHeight) {
    loading.value = true;
    getLibraryItems(page.value).then(r => {
      if (r.length > 0) {
        libraryStore.addAll(r);
        page.value += 1;
        libraryStore.setPage(page.value + 1);
        loading.value = false;
        shouldLoadNextPage();
      } else {
        libraryStore.setAllLoaded(true);
      }
    });
  }
};

const allLoaded = ref<boolean>(libraryStore.allItemsLoaded);
const applicationStore = ApplicationStore();
onMounted(() => {
  applicationStore.$reset();
  libraryStore.$subscribe((_,
                           state: UnwrapRef<LibraryItemStoreType>)  => {
    items.value = state.items;
    allLoaded.value = state.allItemsLoaded;
    page.value = state.page;
  });
  window.addEventListener('scroll', shouldLoadNextPage);
  shouldLoadNextPage();
});

onUnmounted(() => {
  window.removeEventListener('scroll', shouldLoadNextPage);
});

</script>

<template>
  <ItemsGrid v-bind="{
        onClick: (item) => openItem(item),
        items: items
    }"/>
  <div v-if="!allLoaded && !libraryStore.allItemsLoaded" id="loading-trigger" class="m-5 text-center text-5xl">Loading....</div>
</template>
