// frontend/src/UI/Button.tsx
import { FlowComponent } from 'solid-js';

type ButtonProps = {
  readonly onClick?: () => void;
  readonly form?: string;
  readonly type?: 'submit' | 'reset' | 'button';
  readonly className?: string;
}

export const Button: FlowComponent<ButtonProps> = (props) => {
  const className = 'bg-transparent flex justify-center items-center dark:border-slate-200 dark:hover:bg-slate-500 dark:text-slate-50 border-slate-500 ' +
    'hover:bg-slate-400 text-slate-800 font-semibold hover:text-white py-1 px-2 border hover:border-transparent rounded ';
  return (
    <button
      onClick={props.onClick}
      type={props.type}
      form={props.form}
      class={className + (props.className || '')}
    >
      {props.children}
    </button>
  );
};

export const PrimaryButton: FlowComponent<ButtonProps> = (props) => {
  const className = 'dark:bg-red-900 flex justify-center items-center dark:hover:bg-red-800 bg-red-500 hover:bg-red-400 text-white font-bold py-1 px-2 rounded ';
  return (
    <button
      onClick={props.onClick}
      type={props.type}
      form={props.form}
      class={className + (props.className || '')}
    >
      {props.children}
    </button>
  );
};

type LinkButtonProps = {
  readonly download?: boolean;
  readonly href: string;
  readonly className?: string;
};

export const LinkButton: FlowComponent<LinkButtonProps> = (props) => {
  const className = 'w-[100%] text-center flex justify-center items-center cursor-pointer bg-transparent dark:border-slate-200 dark:hover:bg-slate-500 ' +
    'dark:text-slate-50 border-slate-500 hover:bg-slate-400 text-slate-800 font-semibold hover:text-white py-1 px-2 border hover:border-transparent rounded ';
  return (
    <a
      download={props.download}
      href={props.href}
      class={className + (props.className || '')}
    >
      {props.children}
    </a>
  );
};

// frontend/src/UI/Button.vue
<script setup lang="ts">
defineProps<{
  buttonType: 'primary' | 'link' | 'default';
  href?: string;
  download?: boolean;
  className?: string;
  onClick?: () => void;
  type?: "button" | "reset" | "submit";
  form?: string;
}>();
</script>
<template>
  <button
      v-if="buttonType === 'default'"
      v-on:click="onClick"
      v-bind="{
        type,
        form
      }"
      @click="{onClick}"
      class="bg-transparent flex justify-center items-center dark:border-slate-200 dark:hover:bg-slate-500 dark:text-slate-50 border-slate-500 hover:bg-slate-400 text-slate-800 font-semibold hover:text-white py-2 px-4 border hover:border-transparent rounded"
  >
    <slot/>
  </button>
  <button
      v-if="buttonType === 'primary'"
      v-on:click="onClick"
      v-bind="{
        type,
        form
      }"
      class="dark:bg-red-900 flex justify-center items-center dark:hover:bg-red-800 bg-red-500 hover:bg-red-400 text-white font-bold py-2 px-4 rounded"
  >
    <slot/>
  </button>
  <a
      v-bind="{
        href,
        download: download,
        class: 'w-[100%] text-center flex justify-center items-center cursor-pointer bg-transparent dark:border-slate-200 dark:hover:bg-slate-500 dark:text-slate-50 border-slate-500 hover:bg-slate-400 text-slate-800 font-semibold hover:text-white py-2 px-4 border hover:border-transparent rounded'
        + ' '+(className? className : '')
    }"
      v-if="buttonType === 'link'"
  >
    <slot/>
  </a>
</template>
